# -*- coding: utf-8 -*-
"""CryptoAnalysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZ4IpfYBDpoB0GBs0Hm6nX8ZN7TlX482
"""

# This program uses Bitcoin, Ethereum, Litecoin, and Dogecoin to perform a quick analysis. 
import pandas as pd # data analysis 
import numpy as np # arrays

from google.colab import files # import files 
files.upload()

doge = pd.read_csv('coin_Dogecoin.csv') # reads the file and puts the data set into each variable 
bitcoin = pd.read_csv('coin_Bitcoin.csv')
ethereum = pd.read_csv('coin_Ethereum.csv')
litecoin = pd.read_csv('coin_Litecoin.csv')

doge_close = doge['Close'] # get the close price of all the points in the data sets 
bitcoin_close = bitcoin['Close']
ethereum_close = ethereum['Close']
litecoin_close = litecoin['Close']

doge_close.describe() #calculates statistical data

bitcoin_close.describe()

ethereum_close.describe()

litecoin_close.describe()

dsr_litecoin = litecoin_close.pct_change(1) # get the percent change 
dsr_litecoin

dsr_bitcoin = bitcoin_close.pct_change(1)
dsr_bitcoin

dsr_dogecoin = doge_close.pct_change(1)
dsr_dogecoin

dsr_ethereum = ethereum_close.pct_change(1)
dsr_ethereum

print(dsr_litecoin.std()) # find the standard deviation of percent change 
print(dsr_dogecoin.std()) # dogecoin has the highest standard deviation of percent change 
print(dsr_ethereum.std()) # bitcoin has the lowest standard deviation of percent change (more clustered around the mean)
print(dsr_bitcoin.std())

print(dsr_litecoin.mean()) # dogecoin has highest mean average of percent change 
print(dsr_bitcoin.mean()) # bitcoin has the lowest mean average of percent change
print(dsr_dogecoin.mean())
print(dsr_ethereum.mean())